# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/config.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Configurator(object):
    def setupUi(self, Configurator):
        Configurator.setObjectName("Configurator")
        Configurator.resize(467, 205)
        self.verticalLayout = QtWidgets.QVBoxLayout(Configurator)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelAddress = QtWidgets.QLabel(Configurator)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelAddress.setFont(font)
        self.labelAddress.setAlignment(QtCore.Qt.AlignCenter)
        self.labelAddress.setObjectName("labelAddress")
        self.verticalLayout.addWidget(self.labelAddress)
        self.editAddress = QtWidgets.QLineEdit(Configurator)
        self.editAddress.setObjectName("editAddress")
        self.verticalLayout.addWidget(self.editAddress)
        self.labelLogin = QtWidgets.QLabel(Configurator)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelLogin.setFont(font)
        self.labelLogin.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLogin.setObjectName("labelLogin")
        self.verticalLayout.addWidget(self.labelLogin)
        self.editLogin = QtWidgets.QLineEdit(Configurator)
        self.editLogin.setObjectName("editLogin")
        self.verticalLayout.addWidget(self.editLogin)
        self.labelPassword = QtWidgets.QLabel(Configurator)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelPassword.setFont(font)
        self.labelPassword.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPassword.setObjectName("labelPassword")
        self.verticalLayout.addWidget(self.labelPassword)
        self.editPassword = QtWidgets.QLineEdit(Configurator)
        self.editPassword.setObjectName("editPassword")
        self.verticalLayout.addWidget(self.editPassword)
        self.buttonBox = QtWidgets.QDialogButtonBox(Configurator)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Configurator)
        self.buttonBox.accepted.connect(Configurator.accept) # type: ignore
        self.buttonBox.rejected.connect(Configurator.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Configurator)

    def retranslateUi(self, Configurator):
        _translate = QtCore.QCoreApplication.translate
        Configurator.setWindowTitle(_translate("Configurator", "Configurator"))
        self.labelAddress.setText(_translate("Configurator", "Адрес"))
        self.labelLogin.setText(_translate("Configurator", "Логин"))
        self.labelPassword.setText(_translate("Configurator", "Пароль"))
