# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/streams.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Streams(object):
    def setupUi(self, Streams):
        Streams.setObjectName("Streams")
        Streams.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Streams)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listStreams = QtWidgets.QListWidget(Streams)
        self.listStreams.setObjectName("listStreams")
        self.verticalLayout.addWidget(self.listStreams)
        self.buttonDisable = QtWidgets.QPushButton(Streams)
        self.buttonDisable.setObjectName("buttonDisable")
        self.verticalLayout.addWidget(self.buttonDisable)
        self.buttonBox = QtWidgets.QDialogButtonBox(Streams)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Streams)
        self.buttonBox.accepted.connect(Streams.accept) # type: ignore
        self.buttonBox.rejected.connect(Streams.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Streams)

    def retranslateUi(self, Streams):
        _translate = QtCore.QCoreApplication.translate
        Streams.setWindowTitle(_translate("Streams", "Streams"))
        self.buttonDisable.setText(_translate("Streams", "Отключить"))
