# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/template.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Template(object):
    def setupUi(self, Template):
        Template.setObjectName("Template")
        Template.resize(868, 692)
        self.verticalLayout = QtWidgets.QVBoxLayout(Template)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Template)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.edit_title = QtWidgets.QLineEdit(Template)
        self.edit_title.setObjectName("edit_title")
        self.verticalLayout.addWidget(self.edit_title)
        self.labelExample = QtWidgets.QLabel(Template)
        self.labelExample.setObjectName("labelExample")
        self.verticalLayout.addWidget(self.labelExample)
        self.tableSchedule = QtWidgets.QTableWidget(Template)
        self.tableSchedule.setGridStyle(QtCore.Qt.SolidLine)
        self.tableSchedule.setWordWrap(True)
        self.tableSchedule.setCornerButtonEnabled(True)
        self.tableSchedule.setRowCount(25)
        self.tableSchedule.setColumnCount(4)
        self.tableSchedule.setObjectName("tableSchedule")
        item = QtWidgets.QTableWidgetItem()
        icon = QtGui.QIcon.fromTheme("dark")
        item.setIcon(icon)
        self.tableSchedule.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableSchedule.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableSchedule.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableSchedule.setHorizontalHeaderItem(3, item)
        self.tableSchedule.horizontalHeader().setCascadingSectionResizes(True)
        self.tableSchedule.horizontalHeader().setDefaultSectionSize(200)
        self.tableSchedule.horizontalHeader().setSortIndicatorShown(False)
        self.tableSchedule.verticalHeader().setCascadingSectionResizes(True)
        self.verticalLayout.addWidget(self.tableSchedule)
        self.buttonSave = QtWidgets.QPushButton(Template)
        self.buttonSave.setObjectName("buttonSave")
        self.verticalLayout.addWidget(self.buttonSave)

        self.retranslateUi(Template)
        QtCore.QMetaObject.connectSlotsByName(Template)

    def retranslateUi(self, Template):
        _translate = QtCore.QCoreApplication.translate
        Template.setWindowTitle(_translate("Template", "Template"))
        self.label.setText(_translate("Template", "Название шаблона"))
        self.labelExample.setText(_translate("Template", "Пример: | 16:00 | 220 | video1.flv | 47jh-eda2-uzh7..."))
        item = self.tableSchedule.horizontalHeaderItem(0)
        item.setText(_translate("Template", "Время начала"))
        item = self.tableSchedule.horizontalHeaderItem(1)
        item.setText(_translate("Template", "Продолжительность в мин."))
        item = self.tableSchedule.horizontalHeaderItem(2)
        item.setText(_translate("Template", "Название файла"))
        item = self.tableSchedule.horizontalHeaderItem(3)
        item.setText(_translate("Template", "Ссылка трансляции"))
        self.buttonSave.setText(_translate("Template", "Сохранить"))
